//! macOS rollback is scoped to this exact App bundle, never a caller path.
use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};
use tauri::{AppHandle, Manager};

fn app_bundle() -> Result<PathBuf, String> {
    let executable = std::env::current_exe().map_err(|_| "app_bundle_required")?;
    let bundle = executable
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .ok_or("app_bundle_required")?;
    if bundle.extension().and_then(|s| s.to_str()) != Some("app")
        || !bundle.join("Contents/Info.plist").is_file()
    {
        return Err("app_bundle_required".into());
    }
    Ok(bundle.to_path_buf())
}

fn root(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_local_data_dir()
        .map_err(|_| "backup_unavailable")?
        .join("update-backup"))
}
fn copy(source: &Path, destination: &Path) -> Result<(), String> {
    let status = Command::new("ditto")
        .arg(source)
        .arg(destination)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map_err(|_| "backup_failed")?;
    if !status.success() {
        return Err("backup_failed".into());
    }
    let verified = Command::new("codesign")
        .args(["--verify", "--deep", "--strict"])
        .arg(destination)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map_err(|_| "backup_failed")?;
    if !verified.success() {
        return Err("backup_failed".into());
    }
    Ok(())
}

pub fn available(app: &AppHandle) -> bool {
    cfg!(target_os = "macos")
        && root(app).is_ok_and(|r| r.join("previous/LoopX.app/Contents/Info.plist").is_file())
}

pub fn prepare(app: &AppHandle) -> Result<(), String> {
    if !cfg!(target_os = "macos") {
        return Ok(());
    }
    let bundle = app_bundle()?;
    let root = root(app)?;
    fs::create_dir_all(&root).map_err(|_| "backup_failed")?;
    let temporary = tempfile::tempdir_in(&root).map_err(|_| "backup_failed")?;
    copy(&bundle, &temporary.path().join("LoopX.app"))?;
    fs::write(
        temporary.path().join("version"),
        app.package_info().version.to_string(),
    )
    .map_err(|_| "backup_failed")?;
    let previous = root.join("previous");
    // Retain the old backup until the new verified backup is durable. This
    // directory contains only backups generated by this updater.
    if previous.exists() {
        let older = root.join(format!(
            "older-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis()
        ));
        fs::rename(&previous, older).map_err(|_| "backup_failed")?;
    }
    fs::rename(temporary.path(), previous).map_err(|_| "backup_failed")?;
    Ok(())
}

pub fn restore(app: &AppHandle) -> Result<(), String> {
    if !available(app) {
        return Err("backup_unavailable".into());
    }
    let bundle = app_bundle()?;
    let staging = tempfile::tempdir_in(bundle.parent().ok_or("app_bundle_required")?)
        .map_err(|_| "rollback_failed")?;
    let candidate = staging.path().join("LoopX.app");
    copy(&root(app)?.join("previous/LoopX.app"), &candidate)?;
    let failed = staging.path().join("failed.app");
    let version = fs::read_to_string(root(app)?.join("previous/version"))
        .map_err(|_| "backup_unavailable")?;
    // Once an installed App can move here, never let TempDir cleanup erase it
    // on a failed second rename (including a failed restoration rename).
    let _preserved = staging.keep();
    crate::bundled_runtime::record_pending(app, version.trim(), "rollback")?;
    replace_bundle(&bundle, &candidate, &failed)?;
    // Keep the failed App recoverable too. Never delete a user's installed App.
    Ok(())
}

fn replace_bundle(bundle: &Path, candidate: &Path, failed: &Path) -> Result<(), String> {
    fs::rename(bundle, failed).map_err(|_| "rollback_failed")?;
    if fs::rename(candidate, bundle).is_err() {
        let _ = fs::rename(failed, bundle);
        return Err("rollback_failed".into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn failed_replacement_restores_original() {
        let dir = tempfile::tempdir().unwrap();
        let app = dir.path().join("installed.app");
        fs::create_dir(&app).unwrap();
        fs::write(app.join("original"), "keep").unwrap();
        assert!(replace_bundle(
            &app,
            &dir.path().join("missing.app"),
            &dir.path().join("failed.app")
        )
        .is_err());
        assert_eq!(fs::read_to_string(app.join("original")).unwrap(), "keep");
    }

    #[test]
    #[ignore = "requires LOOPX_TEST_APP from a signed macOS build"]
    fn real_backup_copy_retains_signature() {
        let source = std::env::var("LOOPX_TEST_APP").unwrap();
        let dir = tempfile::tempdir().unwrap();
        let copied = dir.path().join("LoopX.app");
        copy(Path::new(&source), &copied).unwrap();
        assert!(copied
            .join("Contents/Resources/runtime/identity.json")
            .is_file());
    }
}
